spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/YoutubeAnalytics
    username: user
    password: user#1

mybatis:
  mapper-locations:
    - classpath:/mapper/**/*.xml
  type-handlers-package: com.loudg.api.yt.handler.type
server:
  port: 3000
